### ISSUE TITLE
peninsulaJS1 todo

### ISSUE THREAD

**Issue by nickdesaulniers** [peninsulajs/peninsulajs.github.io#1]
- [x] Website
- [x] tito ticketing: https://ti.to/peninsulajs
- [x] domain name http://peninsulajs.com
- [x] message desktop about hardware requirements
- [x] Pizzas
- [x] Water
- [x] Rules around food
- [x] CoC
- [x] CFP issue
- [x] attendee list for security

**Comment by nickdesaulniers** [comment]
good to go!
